spring:
  datasource:
    url: jdbc:sap://b292e140-a5e8-4486-9cd8-ebd49e3a6cdc.hana.trial-us10.hanacloud.ondemand.com:443/?encrypt=true&validateCertificate=false
    username: DBADMIN
    password: Bjyxszd@0622
    driver-class-name: com.sap.db.jdbc.Driver
#  web:
#    resources:
#      static-locations:
#        [ classpath:/templates/]
#  thymeleaf:
#    prefix: [classpath:/templates/]
#    suffix: .html



